package no.nav.k9brukerdialogapi.ytelse

enum class Ytelse {
    OMSORGSPENGER_UTVIDET_RETT,
    OMSORGSPENGER_MIDLERTIDIG_ALENE,
    ETTERSENDING,
    OMSORGSDAGER_ALENEOMSORG,
    OMSORGSPENGER_UTBETALING_ARBEIDSTAKER,
    OMSORGSPENGER_UTBETALING_SNF,
    OMSORGSDAGER_MELDING_FORDELING,
    OMSORGSDAGER_MELDING_OVERFORING,
    OMSORGSDAGER_MELDING_KORONAOVERFORING
}