apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
spec:
  image: {{image}}
  port: 8080
  kafka:
    pool: {{kafka-pool}}
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 40m
      memory: 1024Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: omsorgspengesoknad
        - application: ekstra-omsorgsdager-andre-forelder-ikke-tilsyn
        - application: sif-ettersending
        - application: omsorgspengerutbetaling-arbeidstaker-soknad
        - application: omsorgsdager-aleneomsorg-dialog
        - application: omsorgspengerutbetaling-soknad
        - application: pleiepenger-i-livets-sluttfase-soknad
        - application: pleiepengesoknad
        - application: sif-innsyn
        - application: endringsmelding-pleiepenger
    outbound:
      rules:
        - application: k9-mellomlagring
        - application: k9-brukerdialog-cache
        - application: k9-selvbetjening-oppslag
        - application: sif-innsyn-api
      external:
      {{#each externalHosts as |host|}}
          - host: {{host}}
      {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  envFrom:
    - secret: {{app}}

